<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Rewind.Agent.Core/Rewind.Agent.Core.csproj" />
    <ProjectReference Include="../../src/Rewind.Protocol/Rewind.Protocol.csproj" />
    <ProjectReference Include="../../src/Rewind.Sdk/Rewind.Sdk.csproj" />
    <ProjectReference Include="../../src/Rewind.Storage/Rewind.Storage.csproj" />
  </ItemGroup>
</Project>
